# Generated by Django 4.2.2 on 2023-07-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('passUsuario', models.CharField(max_length=50)),
            ],
        ),
    ]
