# Generated by Django 4.2.1 on 2023-07-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
